#!/bin/bash

# Upgrade und Aufräumen mit nala und flatpak
echo -e "\n\n#### APT-Update und -Upgrade #############\n"
apt update || { echo "ERROR: APT Update failed."; exit 1; }
apt upgrade -y || { echo "ERROR: APT Upgrade failed."; exit 1; }
echo -e "\n\n#### APT-Autoremove ######################\n"
apt autoremove -y || { echo "ERROR: nala autopurge failed."; exit 1; }
echo -e "\n\n#### Flatpak-Update ######################\n"
flatpak update -y || { echo "ERROR: flatpak update failed."; exit 1; }
echo -e "\n\n#### Flatpak-Autoremove ##################\n"
flatpak uninstall --unused -y || { echo "ERROR: flatpak uninstall failed."; exit 1; }


