#!/bin/bash

# Farben definieren
YELLOW="\033[1;33m"
RESET="\033[0m"

# Upgrade und Aufräumen mit nala und flatpak
flatpak update -y || { echo "ERROR: nala update failed."; exit 1; }

# Erfolgreicher Abschluss
echo "All commands completed successfully."

# Terminal offen halten mit farbiger Meldung
echo -e "${YELLOW}Press Enter to close.${RESET}"
read -p ""