#!/bin/bash

# Überprüfen, ob Wine installiert ist
if ! command -v wine &> /dev/null; then
    echo "Wine ist nicht installiert. Installation wird gestartet."

    sudo dpkg --add-architecture i386
    sudo mkdir -pm755 /etc/apt/keyrings
    sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
    sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/debian/dists/bookworm/winehq-bookworm.sources
    sudo apt update
    sudo apt install -y --install-recommends winehq-stable
else
    echo "Wine ist bereits installiert."
fi