#!/bin/bash

set -e  # Skript beendet sich bei Fehlern

# Funktion zur Fehlerausgabe
error_exit() {
    echo "Fehler: $1" >&2
    exit 1
}

# Überprüfen, ob Wine installiert ist
if ! command -v wine &> /dev/null; then
    echo "Wine ist nicht installiert. Installation wird gestartet."
    
    sudo dpkg --add-architecture i386 || error_exit "Fehler beim Hinzufügen der i386-Architektur"
    sudo mkdir -pm755 /etc/apt/keyrings || error_exit "Fehler beim Erstellen von /etc/apt/keyrings"
    sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key || error_exit "Fehler beim Herunterladen des WineHQ-Schlüssels"
    sudo wget -NP /etc/apt/sources.list.d/ "https://dl.winehq.org/wine-builds/ubuntu/dists/$(lsb_release -c | grep -o '\w*$')/winehq-$(lsb_release -c | grep -o '\w*$').sources"
    sudo apt update || error_exit "Fehler beim Aktualisieren der Paketliste"
    sudo apt install -y --install-recommends winehq-stable || error_exit "Fehler bei der Installation von WineHQ-Stable"
    echo "Wine wurde erfolgreich installiert."
else
    echo "Wine ist bereits installiert."
fi

# Lutris installieren
echo "Lutris wird installiert."
sudo apt install -y lutris || error_exit "Fehler bei der Installation von Lutris"
echo "Lutris wurde erfolgreich installiert."

# winecfg ausführen
echo "Wine Konfiguration wird gestartet..."
sudo apt install -y mono-complete
echo "Wine Konfiguration abgeschlossen."
