#!/bin/bash

# Schritt 2: Installation der .deb-Datei mit pkexec und apt
echo "Installiere Steam über apt..."
sudo dpkg --add-architecture i386 && sudo apt install -y steam-installer libgl1-mesa-dri:i386 mesa-vulkan-drivers mesa-vulkan-drivers:i386 || error_exit "Installation fehlgeschlagen"

# Schritt 3: Erfolgsmeldung
echo "Installation von Steam erfolgreich abgeschlossen!"
