#!/bin/bash

error_exit() {
	echo "$1" 1>&2
	exit 1
}

echo "Installiere Steam über apt..."
sudo dpkg --add-architecture i386

sudo apt update || error_exit "Update fehlgeschlagen"

sudo apt install -y steam-installer libgl1-mesa-dri:i386 mesa-vulkan-drivers mesa-vulkan-drivers:i386 || error_exit "Installation fehlgeschlagen"

echo "Installation von Steam erfolgreich abgeschlossen!"
