#!/bin/bash

sudo apt remove -y brave-browser


sudo rm -f \
    /etc/apt/sources.list.d/brave-browser-release.list \
    /usr/share/keyrings/brave-browser-archive-keyring.gpg \
    /usr/share/keyrings/brave-browser-beta-archive-keyring.gpg \
    /usr/share/keyrings/brave-browser-nightly-archive-keyring.gpg

