#!/bin/bash

# Install FreeOffice 2021
wget -qO- https://shop.softmaker.com/repo/linux-repo-public.key | gpg --dearmor > softmaker.gpg
cat softmaker.gpg | sudo tee /usr/share/keyrings/softmaker.gpg > /dev/null
echo "deb [signed-by=/usr/share/keyrings/softmaker.gpg] https://shop.softmaker.com/repo/apt stable non-free" | sudo tee /etc/apt/sources.list.d/softmaker.list
sudo apt update
sudo apt install softmaker-freeoffice-2024 -y
